### ISSUE TITLE
Reading into multiple maildirs

### ISSUE THREAD

**Issue by clwgg** [sulami/feed2maildir#4]
Hi!
I was wondering if it is possible to read a set of feeds into different maildirs? something like
```
{
    "db": "~/.f2mdb",
{
    "maildir": "~/mail/feeds1",
    "feeds": {
        "Commit Strip": "http://www.commitstrip.com/en/feed/",
        "XKCD": "http://xkcd.com/rss.xml",
    }
}
{
    "maildir": "~/mail/feeds2",
    "feeds": {
        "Dilbert": "http://feed.dilbert.com/dilbert/daily_strip?format=xml",
        "BSDNow": "http://feeds.feedburner.com/BsdNowOgg"
    }
}
}
```

My understanding is, that this behavior is not supported? So I was wondering if you think it might be a desirable addition? Or would it be difficult to add? If you think it is desirable but don't have time to work on it, I could try myself on a PR -- but wanted to check in first before I spend any time on it.

Thanks!

**Comment by sulami** [comment]
Hey,

currently this is not supported, but I wouldn't be opposed to having it added, if you wanted to submit a PR.
